SSstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('', RedirectView.as_view(url='/store/')),
    path('admin/', admin.site.urls),
    path('store/', include('e_store.urls', namespace='store')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from accounts import views


app_name='accounts'
urlpatterns = [
    path('register/', views.register_account, name="register_account"),
    path('logout/', views.logout_account, name="logout"),
    path('login/', views.login_account, name='login'),
    path('profile/', views.profile_view, name='profile'),
]

e_store/urls.py
from django.urls import path, include
from e_store import views


app_name='store'


urlpatterns = [
    path('', views.store_view, name="store_view"),
    path('detail/<str:code>', views.product_detail_view, name="product_detail"),
    path('add_to_cart/', views.cart_ajax_handler, name="ajax_add_to_cart"),
    path('set_address/', views.set_address_view, name="set_address"),
    path('checkout/', views.checkout_view, name="checkout"),
    path('checkout/placeorder/', views.placeorder_ajax, name='ajax_placeorder'),
    path('autocomplete/', views.autocomplete_ajax, name='autocomplete_ajax')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager



class AccountManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, mobile, password=None):
        if not email:
            raise ValueError('Users must have an email')
        if not username:
            raise ValueError('Users must have an username')
        if not first_name:
            raise ValueError('Users must have a first name')
        if not last_name:
            raise ValueError('Users must have a last_name')
        if not mobile:
            raise ValueError('Users must have a mobile')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            mobile=mobile,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, username, first_name, last_name, mobile, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            mobile=mobile,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user




class User(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", unique=True, max_length=30)
    mobile = models.CharField(max_length=11, verbose_name="Mobile Number")
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=30, verbose_name="First Name")
    last_name = models.CharField(max_length=30, verbose_name="Last Name")
    

    date_joined = models.DateTimeField(verbose_name="Date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="Last login", auto_now_add=True)

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name', 'mobile']

    objects = AccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perms, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from django import forms
from accounts.models import User
from e_store.models import Address, Order, OrderItem

class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=30, help_text="Required: Add a valid email address")

    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', 'mobile', 'password1', 'password2']


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['name', 'mobile', 'region', 'province', 'city', 'brgy_dist_name','postal_code', 'detailed_address']



class LoginUserForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        if not authenticate(email=email, password=password):
            raise forms.ValidationError("Invalid Login")


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'mobile', 'ship_address', 'transaction_id', 'payment_type']

class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['quantity','total_price','product']

    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from accounts.forms import RegisterForm, LoginUserForm
from e_store.models import Address
from accounts.models import User
from django.views.generic.base import RedirectView
from django.contrib import messages
# Create your views here.

def register_account(request):
    context = {}
    if request.POST: 
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            message.success(request, 'Registered successfully')
            return redirect('store:store_view')
        else:
            context['form_set'] = form
    else:
        form = RegisterForm()
        context['form_set'] = form
    return render(request, 'accounts/register.html', context)

def logout_account(request):
    logout(request)
    return render(request, 'accounts/logout.html')




def login_account(request):
    user = request.user
    if user.is_authenticated:
        return redirect('store:store_view')
    context = {}
    if request.POST:
        form = LoginUserForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                messages.success(request, "Login successful")
                return redirect('store:store_view')
        else:
            form = LoginUserForm(request.POST)
            context['form'] = form
    else: #GET request
        form = LoginUserForm()
        context['form'] = form
    return render(request, 'accounts/login.html', context)
    
    

def profile_view(request):
    user = request.user
    if user.is_authenticated:
        context = {}
        context['address'] = user.addresses.all()
        context['order'] = user.order_set.all()
    else:
        messages.warning(request, "Please login first")
        return redirect('accounts:login')
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/login.html
{% extends 'e_store/base.html' %} 
{% load crispy_forms_tags %} 


{% block content %}
{% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }} h4 text-center d-block bg-danger text-light"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
{% endif %}
<div class="row justify-content-center">
  <div class="d-block border border-primary rounded-corner col-4 m-0 p-0">
    <h2 class="bg-primary text-light text-center d-block">
      Login
    </h2>
    {% if message %}
    <div class="h2 text-danger text-center">{{message}}</div>
    {% endif %}
    <div class="p-3">
      <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %} 
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'e_store/base.html' %}

{% block content %}

<div class="d-block text-center">
    <h2 class="m-auto">
        You are logging out
    </h2>
    <h2 id='check'>

    </h2>
</div>
<script type="text/javascript">
var delay = 2000; 
setTimeout(function(){ window.location = "{% url 'store:store_view' %}"; }, delay);
</script>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'e_store/base.html' %}


{% block content %}

<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-home" aria-selected="true">Profile</a>
      <a class="nav-item nav-link" id="nav-address-tab" data-toggle="tab" href="#nav-address" role="tab" aria-controls="nav-profile" aria-selected="false">Address</a>
      <a class="nav-item nav-link" id="nav-orders-tab" data-toggle="tab" href="#nav-orders" role="tab" aria-controls="nav-contact" aria-selected="false">Orders</a>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-home-tab">
        <div class="row m-0 p-0">
            <div class="col-12">
                <div class="row m-0 p-0">
                    <div class="col-12">
                        Username: <span class="font-weight-bold">{{user.username}}</span>
                    </div>
                    <div class="col-12">
                        Email:<span class="">{{user.email}}</span>
                    </div>
                    <div class="col-12">
                        Name:<span class="">{{user.first_name}}</span>
                    </div>
                </div>
            </div>
        
        </div>
        
    </div>
    <div class="tab-pane fade" id="nav-address" role="tabpanel" aria-labelledby="nav-profile-tab">
        <h4 class="h4 text-weight-bold text-primary">Address</h4>
        {% if address %}
            <div class="table-responsive">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Complete Address</th>
                    <th scope="col">Name</th>
                    <th scope="col">Mobile</th>
                    <th scope="col">Current</th>
                    <th scope="col">Edit</th>
                  </tr>
                </thead>
                <tbody>
                {% for i in  address %}
                  <tr>
                    <th scope="row">{{ i.get_complete_address}}</th>
                    <td>{{i.name}}</td>
                    <td>{{i.mobile}}</td>
                    <td class="text-center">
                        {% if i.current %} 
                        <span style="color: Dodgerblue;">
                        <i class="fas fa-check-square"></i>
                    </span>
                        {% else %}
                        <span style="color: Dodgerblue;">
                        <i class="far fa-square"></i>
                    </span>
                        {% endif %}
                    </td>
                    <td><a href="#">Edit</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          <a href="#" class="text-primary"><p>Add another address <span style="color: green;"><i class="fas fa-plus"></i></span>
          </p></a>
        {% else %}
        <p>No address yet. Please add one by clicking <a class="text-primary" href="{% url 'store:set_address' %}">here</a></p>
        {% endif %}
    </div>
    <div class="tab-pane fade" id="nav-orders" role="tabpanel" aria-labelledby="nav-contact-tab">
        <h4 class="h4 text-weight-bold text-primary">Address</h4>
        {% if order %}
        <div class="table-responsive">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Date ordered</th>
                    <th scope="col">Transaction ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Payment Type</th>
                    <th scope="col">Delivered</th>
                    <th scope="col">Details</th>
                  </tr>
                </thead>
                <tbody>
                {% for i in order %}
                  <tr>
                    <th scope="row">{{ i.date_ordered}}</th>
                    <td>{{i.transaction_id}}</td>
                    <td>{{i.name}}</td>
                    <td>{{i.payment_type}}</td>
                    <td class="text-center">
                        {% if i.complete %}
                        <span style="color: Dodgerblue;">
                        <i class="fas fa-check-square"></i>
                        </span>
                        {% else %}
                        <span style="color: Dodgerblue;">
                        <i class="far fa-square"></i>
                        </span>
                        {% endif %}
                    </td>
                    <td><a href="#">Details</a></td>
                  </tr>
                  {% endfor %}
                  
                </tbody>
              </table>
            </div>
            <a href="#" class="text-primary"><p>Make an order by shopping here <span style="color: green;"><i class="fas fa-plus"></i></span>
            </p></a>
        {% else %}
        <p>No orders yet. Do some shopping first by clicking <a class="text-primary" href="{% url 'store:store_view' %}">here</a></p>
        {% endif %}
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'e_store/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-6 m-auto">
    <h2>Register</h2>
    <form action="{%url 'accounts:register_account' %}" method="post">
        {% csrf_token %}
        {{ form_set|crispy }}       
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>
{% endblock %}