SSstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('', RedirectView.as_view(url='/store/')),
    path('admin/', admin.site.urls),
    path('store/', include('e_store.urls', namespace='store')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from accounts import views


app_name='accounts'
urlpatterns = [
    path('register/', views.register_account, name="register_account"),
    path('logout/', views.logout_account, name="logout"),
    path('login/', views.login_account, name='login'),
    path('profile/', views.profile_view, name='profile'),
]

e_store/urls.py
from django.urls import path, include
from e_store import views


app_name='store'


urlpatterns = [
    path('', views.store_view, name="store_view"),
    path('detail/<str:code>', views.product_detail_view, name="product_detail"),
    path('add_to_cart/', views.cart_ajax_handler, name="ajax_add_to_cart"),
    path('set_address/', views.set_address_view, name="set_address"),
    path('checkout/', views.checkout_view, name="checkout"),
    path('checkout/placeorder/', views.placeorder_ajax, name='ajax_placeorder'),
    path('autocomplete/', views.autocomplete_ajax, name='autocomplete_ajax')
]

e_store/models.py
from django.db import models
from django.shortcuts import reverse
# Create your models here.


class Product(models.Model):

    class ProductCategory(models.TextChoices):
        CANNED = 'Canned Goods', ('Canned Goods')
        NOODLES = 'Noodles', ('Noodles')
        VEGGIES = 'Vegetables', ('Vegetables')
        RICE = 'Rice', ('Rice')

    
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=20, choices=ProductCategory.choices, default=ProductCategory.CANNED)
    price = models.IntegerField(default=1)

    def __str__(self):
        return self.name

    def get_id(self):
        return self.id

    def get_detail_url(self):
        return reverse('store:product_detail', kwargs={'code' : self.code})

    def get_images(self):
        return self.images.all()

    def get_thumbnail(self):
        return self.images.get(num=1).image.url


class Images(models.Model):
    num = models.IntegerField(default=0)
    product = models.ForeignKey(Product, related_name="images", on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products', null=True, blank=True)


class Order(models.Model):

    class PayChoices(models.TextChoices):
        COD = 'Cash on Delivery', ('Cash on Delivery')
        PAYMAYA = 'PayMaya', ('PayMaya')
        GCASH = 'Gcash', ('Gcash')
        BANK = 'Bank', ('Bank')


    customer = models.ForeignKey('accounts.User', null=True, blank=True, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)
    ship_address = models.CharField(max_length=100, verbose_name="Delivered to", default="address") 
    payment_type = models.CharField(max_length=20, choices=PayChoices.choices, default=PayChoices.COD,verbose_name="Payment Method")
    name = models.CharField(max_length=40, verbose_name="Name", default='Name')
    mobile = models.CharField(max_length=11, verbose_name="Mobile No.", default='09')
 

    def __str__(self):
        return str(self.name) + " " + self.mobile

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    @property
    def total_payment(self):
        orderitems = self.orderitem_set_all()
        total_pay = sum([item.total_price for item in orderitems])
        return total_pay

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True)
    quantity = models.IntegerField(default=1)
    total_price = models.IntegerField(default=0)

    @property
    def get_total(self):
        return self.total_price
    

class Address(models.Model):
    customer = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='addresses')
    detailed_address = models.CharField(max_length=20, verbose_name="Detailed Address: House#/Buildingname/Street", default="address")
    brgy_dist_name = models.CharField(max_length=20, verbose_name="Barangay")
    city = models.CharField(max_length=20, verbose_name="City")
    region = models.CharField(max_length=20, verbose_name="Region", default="address")
    province = models.CharField(max_length=20, verbose_name="Province")
    postal_code = models.CharField(max_length=20, verbose_name="Postal Code", default="postal_code here")
    name = models.CharField(max_length=20, verbose_name="Name", default="Please put your name")
    mobile = models.CharField(max_length=20, verbose_name="Mobile #", default="Please update your number")
    distance_to_store = models.IntegerField(default=0, verbose_name="Shipping Distance(km)")
    current = models.BooleanField(default=True)

    @property
    def get_est_fee(self):
        fee_per_km = 8
        initial_fee = 60
        additional_fee = initial_fee + int(round(self.distance_to_store))*fee_per_km
        default = 200
        return default

    @property
    def get_complete_address(self):
        address1 =  self.detailed_address + " " + self.brgy_dist_name
        address2 =  self.region + "~" + self.province
        address3 =  self.city + " " + self.postal_code
        address = address1 + " " + address2+ " " + address3
        return address

    @property
    def get_mobile(self):
        return self.mobile

    @property
    def get_name(self):
        return self.name

    def __str__(self):
        return "Owner: " + str(self.customer) + "Address: " + str(self.get_complete_address)


    

    

e_store/views.py
from django.shortcuts import render, redirect, reverse
from rest_framework import status
from e_store.models import Product, Address, Order
from rest_framework.response import Response
from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import JSONParser
from .api.serializers import ProductSerializer, OrderSerializer
from accounts.forms import AddressForm, OrderForm
from django.forms import inlineformset_factory, modelformset_factory
from accounts.models import User
from django.contrib import messages
from e_store.utils import pay_choice_converter, create_orderitems, create_transaction_id
# Create your views here.


def store_view(request):
    success = messages.get_messages(request)
    search = request.GET.get('name')
    if search != None:
        obj = Product.objects.filter(name__icontains=search)
    else:
        obj = Product.objects.all()
    context = {
        'obj' : obj,
        'messages': success
    }
    return render(request, 'e_store/store.html', context)

def product_detail_view(request, code):
    obj = Product.objects.get(code=code)
    context = {
        "product" : obj,
    }
    return render(request, 'e_store/details.html', context)

@api_view(['GET'])
@parser_classes([JSONParser])
def cart_ajax_handler(request):
    if request.method == 'GET':
        print(request.query_params)
        prod_code = request.query_params.get('code')
        if prod_code == None:
            raise Exception('prod_code is None')
        print(prod_code)
        try:
            obj = Product.objects.get(code=prod_code)
        except Product.DoesNotExist:
            return Response(status=404)
        serializer =  ProductSerializer(obj)
        if request.is_ajax():
            return Response(serializer.data, status=200)
        


def set_address_view(request):
    user = request.user
    context = {}
    context['messages'] = messages.get_messages(request)
    if user.is_authenticated:
        if request.POST:
            form = AddressForm(request.POST)
            if form.is_valid:
                profile = form.save(commit=False)
                profile.customer = request.user
                profile.save()
                messages.success(request, 'Address added successfullly')
                return redirect('store:store_view')
            else:
                form = AddressForm(request.POST)
                context['ship_form'] = ship_form
        else:
            ship_form = AddressForm()
            context['ship_form'] = ship_form
    else:
        messages.warning(request, 'Please login first')
        return redirect('accounts:login')
    return render(request, 'e_store/set_address.html', context)



def checkout_view(request):
    user = request.user
    if user.is_authenticated:
            if (user.addresses.all().exists()):
                address = request.user.addresses.all().get(current=True)
                context = {
                    'address' : address
                }
            else:
                messages.warning(request, 'Please set an address first')
                return redirect('store:set_address')
    else:
        messages.warning(request, 'Please login first')
        return redirect('accounts:login')      
    return render(request, 'e_store/checkout.html', context)


@api_view(['POST'])
@parser_classes([JSONParser])
def placeorder_ajax(request, format=None):
    user = request.user
    if request.method == 'POST':
        payment = request.data.get('payment')
        if payment == None:
            raise Exception("Sorry, payment variable is None.")
        address = request.user.addresses.all().get(current=True)
        data = {
            'name' : address.name,
            'mobile' : address.mobile,
            'transaction_id' : create_transaction_id(),
            'ship_address' : address.get_complete_address,
            'payment_type' : pay_choice_converter(payment),
        }
        form = OrderForm(data)
        if form.is_valid():
            items = request.data.get('products')
            if items == None:
                raise Exception("Sorry, items variable is None.")
            order = form.save(commit=False)
            order.customer = user
            order.save()
            create_orderitems(order, items)
            obj = Order.objects.get(transaction_id=order.transaction_id)
            serializer = OrderSerializer(obj)
            if request.is_ajax():
                return Response(serializer.data, status=200)
        else:
            return Response(form.errors.as_json(), status=500)
            


@api_view(['GET'])
@parser_classes([JSONParser])
def autocomplete_ajax(request):
    if request.method == 'GET':
        input = request.query_params.get('input')
        if input == None:
            raise Exception("input is None")
        print(input)
        try:
            obj = Product.objects.filter(name__icontains=input)[:5]
        except Product.DoesNotExist:
            return Response(status=404)
        serializer = ProductSerializer(obj, many=True)
        if request.is_ajax():
            return Response(serializer.data, status=200)
    else:
        return Response(status=405)

e_store/templates/e_store/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'e_store/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    {% block specific_scripts %}
    {% endblock %}

    <title>Online Shop for your business</title>
  </head>
  <body>
    {% block cart_panel %}
    {% endblock %}
    
    {% block nav %}
    <header class="mb-2">
      <nav class="navbar navbar-expand-lg navbar-light bg-primary text-center">
        
        <a class="navbar-brand text-light" href="{% url 'store:store_view' %}">Online store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menunavbar" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
          
        <div class="collapse navbar-collapse text-center" id="menunavbar">
          
          <form class="form-inline ml-auto my-2 my-lg-0 input-group input-size-md d-none d-md-flex">
            <input class="form-control input-corners" type="search" placeholder="Search">
            <div class="input-group-append">
              <button class="btn btn-light text-primary  btn-corners" type="submit">Go</button>
            </div>
          </form>
        <a class="openbtn my-sm-0 my-2 ml-2 d-none d-md-block" href="">
          <img class="cart-icon" src="{% static 'e_store/img/cart.png' %}"> 
          <span class='in-cart'></span>
        </a>
  
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link menu-link text-light" href="{%url 'store:store_view'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link menu-link text-light" href="#">Products</a>
            </li>
            {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'accounts:profile' %}">Profile</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'accounts:register_account' %}">Sign up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'accounts:login' %}">Login</a>
          </li>
          {% endif%}
          </ul>
        </div>
      </nav>
      <h1 class="jumbotron text-center">
          Online Shop
      </h1>
      
  </header>    
  {% endblock %}
  {% block modal %}

  {% endblock %}

    

    {% block content %}
    <h1> this is the content part</h1>
    {% endblock %}
    {% block footer %}

    {% endblock %}
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script
  src="https://code.jquery.com/jquery-3.5.1.js"
  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" 
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="{% static 'e_store/jsscripts.js' %}"></script>

  </body>
</html>

e_store/templates/e_store/checkout.html
{% extends 'e_store/base.html' %}

{% load crispy_forms_tags %} 

{%load static %}

{% block modal %}

<!-- Modal -->
<div class="modal fade" id="placeordermodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title " id="exampleModalCenterTitle">Transaction complete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h4 class="text-success text-center font-weight-bold">Thank you for buying to us!</h4>
        <p class="text-center">You may check all your orders in details at your profile page.
          Redirecting to home.
        </p>
        <p id="transaction_id_ajax"></p>
        <p id="payment_type_ajax"></p>
        <p id="name_ajax"></p>
        <p id="mobile_ajax"></p>
      </div>
      
    </div>
  </div>
</div>

{% endblock %}



{% block content%}
<div class="text-center">
  <h2 class="h2 d-block bg-primary text-light">Checkout Details</h2>
</div>
<div class="row col-md-6 col-lg-12">
  <div class="cart-items-div col-md-6 col-12" id="update-panel">
    
  </div>
  <div class="col-12 col-md-6">
    {% if address %}
      {% csrf_token %}
      <div class="address-div d-flex justify-content-between">
        <div class="col-6 text-center">
          <span class="text-weight-bold">Address:</span>
        </div>
        <div class="font-weight-bold tex-center">
          {% for i in address.get_complete_address %}{{ i }}{% endfor %}
        </div>
      </div>
      <div class="name-div d-flex justify-content-between">
        <div class="col-6 text-center">
          <span class="text-weight-bold">Name:</span>
        </div>
          <div class="font-weight-bold text-center col-6 text-center">
            {{ address.name }}
          </div>
      </div>
      <div class="contact-div d-flex justify-content-between">
        <div class="col-6 text-center">
          <span class="text-weight-bold">Mobile:</span>
        </div>
          <div class="font-weight-bold text-center col-6">
            {{ address.mobile }}
          </div>
      </div>
      <div class="cart-subtotal-div d-flex justify-content-between">
        <div class="col-6 text-center ">
          <span class="text-weight-bold">Cart Subtotal:</span>
          
        </div>
          <div class="font-weight-bold text-center col-6 ">
            <span class="currency">₱</span>
            <span class="cart-sub-total"></span>  
          </div>
      </div>
      <div class="shippping-div d-flex justify-content-between">
        <div class="col-6 text-center">
          <span class="text-weight-bold ">Shipping Fee:</span>
        </div>
          <div class="font-weight-bold text-center col-6">
            <span class="currency">₱</span>
            <span class="ship_fee">{{ address.get_est_fee }}</span>
          </div>
      </div>
      <div class="total-pay-div d-flex justify-content-between">
        <div class="col-6 text-center">
          <span class="text-weight-bold ">Total Payment:</span>
        </div>
          <div class="font-weight-bold text-center col-6">
            <span class="currency">₱</span>
            <span class="total_payment"></span>
          </div>
      </div>
      <div class="cod-div d-flex justify-content-between">
        <div class="col-6 text-center">
          <span class="text-weight-bold">Payment:</span>
        </div>
        <div class="col-6 text-center">
          <select class="form-control" id="pay-method">
            <option value="COD" selected >Cash on Delivery</option>
            <option value="PayMaya">Pay via PayMaya</option>
            <option value="Gcash">Pay via Gcash</option>
            <option value="Bank">Pay via bank</option>
          </select>
            </div>
      </div>
      <div class="button-divs row text-right">
        <div class="col-12 my-2">
          <button class="place-order btn btn-danger btn-small" href="#">Place Order</button>
        </div>
      </div>
      {% endif %}
  </div>
</div>

{% endblock %}

e_store/templates/e_store/details.html
{% extends "e_store/base.html" %}

{% load static %}

{% block content %}
{% if product %}
<div class="product_details row m-0">

    <div class="image_panel col-12 col-md-8">
      <div class="item-card-image image-detail text-center border border-primary">
        <img src="{{ product.get_thumbnail }}" alt="{{product.name}}" class="mx-auto" >
      </div>
    </div>
    <div class="context_panel col-12 col-md-4">
        <div class="name_panel text-md-left  text-center my-2 ">
            <h3 class="font-weight-bold text-primary" >{{product.name}}</h5>
        </div>
        <div class="price_panel text-left my-2">
            ₱{{product.price}}
        </div>
        <div class="category_panel text-left my-2">
            Category : {{product.category}}
        </div>
        <div class="quantity text-left my-2">
            <button class="btn btn-primary minus" data-product-code="{{product.code}}"> 
              -
            </button>
            <span class="p-3">1</span>
            <button class="btn btn-primary plus" data-product-code="{{product.code}}"> 
              +
            </button>
            </div>
            <div class="link_panel">
              <button class="btn btn-primary btn-block font-weight-bold">Add to cart</button>
            </div>
        </div>
        
    </div>
    

</div>
{% endif %}
{% endblock%}

e_store/templates/e_store/set_address.html
{% extends 'e_store/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li {% if message.tags %} class="text-center h4 d-block {{ message.tags }} bg-danger text-light"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
  {% endif %}
<div>
    <h2 class="h2 d-block bg-primary text-light text-center">Set up your address</h2>
  </div>
  <div class="row m-0 p-0 justify-content-center">
    <div class="col-12 col-md-6">
      <form action="" method="POST">
        {% csrf_token%}
      {{ship_form|crispy}}
      <button type="submit" class="btn btn-primary" >Submit Address</button>
    </form>
    </div>
</div>

  {% endblock %}

e_store/templates/e_store/store.html
{% extends 'e_store/base.html' %} 

{% load static %} 

{% block nav%}
<header class="mb-2">
    <nav class="navbar navbar-expand-lg navbar-light bg-primary text-center">
      
      <a class="navbar-brand text-light" href="#">Online store</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menunavbar" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
        
      <div class="collapse navbar-collapse text-center" id="menunavbar">
        <form class="form-inline ml-auto my-2 my-lg-0 input-group autocomplete-parent input-size-md d-none d-md-flex" method="GET" action="{% url 'store:store_view' %}">
          <input class="form-control search-bar" name="name" type="search" placeholder="Search" >
          <div class="input-group-append">
            <button class="btn btn-light text-primary " type="submit"><i class="fas fa-search"></i></button>
          </div>
          <div class='autocomplete-items'></div>
        </form>
      <a class="openbtn my-sm-0 my-2 ml-2 d-none d-md-block" href="">
        <img class="cart-icon" src="{% static 'e_store/img/cart.png' %}"> 
        <span class='in-cart'></span>
      </a>

        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'store:store_view' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'store:store_view' %}">Products</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'accounts:profile' %}">Profile</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'accounts:register_account' %}">Sign up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link menu-link text-light" href="{% url 'accounts:login' %}">Login</a>
          </li>
          {% endif%}
        </ul>
      </div>
    </nav>
    <h1 class="jumbotron text-center">
        Online Shop
    </h1>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }} h4 text-center d-block bg-success text-light"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

</header>

{% endblock %}

{% block content %}
<div class="contents row m-0">
    <div class="category-panel col-12 col-md-2 ">
      <button class="btn btn-primary btn-block mobile-add-btn d-md-none" >
        <i class="fa fa-shopping-cart" style="font-size:48px;color:white"></i><span class="cart-total"></span>
      </button>
      <form class="form-inline ml-auto my-2 my-lg-0 input-group input-size-md  d-md-none autocomplete-parent" action="" method="GET">
        
        <input class="form-control border-primary  search-bar"  type="search" placeholder="Search">
        <div class="input-group-append">
          <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i>
          </button>
        </div>
        <div class='autocomplete-items'></div>
      </form>
        <div class="collapse-control">
        <h5 class="text-left">
        <a class="text-primary  text-weight-bold" data-toggle="collapse" href="#categories" role="button" aria-expanded="false" aria-controls="collapseExample">
            Show Categories
        </a>
        </h5>
        </div>
        
        <div class="collapse text-left " id="categories">
            <h4>
                Categories:
            </h4>
            <ul class="prod_types">
                <li><a href="#" class="text-light bg-primary px-1">All Products</a></li>    
                <li><a href="#" class="text-primary"><strong>> </strong>Dairy - Milk and Eggs</a></li>    
                <li><a href="#" class="text-primary"><strong>> </strong>Canned & Packaged Goods</a></li>    
                <li><a href="#" class="text-primary"><strong>> </strong>Soups, Noodles & Pasta</a></li>    
                <li><a href="#" class="text-primary"><strong>> </strong>Snacks</a></li>    
                <li><a href="#" class="text-primary"><strong>> </strong>Chocolates & Candies</a></li>    
                <li><a href="#" class="text-primary"><strong>> </strong>Beverages</a></li>    
                <li><a href="#" class="text-primary"><strong>> </strong>Cooking Items & Condiments</a></li>    
            </ul>
        </div>
        <div class="collapse-control">
          <h5 class="text-left">
          <a class="text-primary  text-weight-bold" data-toggle="collapse" href="#OrderBy" role="button" aria-expanded="false" aria-controls="collapseExample">
              Show Order
          </a>
          </h5>
          </div>
        <div class="collapse text-left " id="OrderBy">
          <h4>
              Order by:
          </h4>
          <ul class="prod_types">
              <li><a href="#" class="text-primary"><strong>> </strong>Price: Highest to Lowest</a></li>    
              <li><a href="#" class="text-primary"><strong>> </strong>Price: Lowest to Highest</a></li>    
              <li><a href="#" class="text-primary"><strong>> </strong>Alphabetical: A to Z</a></li>    
              <li><a href="#" class="text-primary"><strong>> </strong>Alphabetical: Z to A</a></li>    
          </ul>
      </div>  
    
    </div>
<div class="product-panel m-0 col-12 col-md-10">
  <div class="row justify-content-between ">
  
  {% for i in obj %}
  <div class="col-12 col-md-6 col-xl-4 text-center my-3">
    <div class="item-card my-1" >
        <div class="item-card-image">
          <img
            src="{{ i.get_thumbnail }}"
            alt="{{ i.name }}"
          />
        </div>
        <div class="item-card-context text-center">
            <div class="item-title-span">
              {{ i.name }}
            </div>
          <div class="item-price my-2">
            
              <span class="item-price-currency">₱ </span>
              <span class="item-price-number">{{ i.price }} </span>
            
          </div>
          <div class="item-links row">
            <div class="add-to-cart-link text-center col-6">
            <h5>
          <a class="add-to-cart text-primary ml-auto" href="#"  data-product-code="{{ i.code }}">
            Add to cart
          </a>
        </h5>
        </div>
        <div class="detail-link text-center col-6">
          <h5>
          <a href="{{ i.get_detail_url }}" class="text-primary ml-auto">
            View
          </a>
        </h5>
        </div>
        </div>
        </div>
      
    </div>
    </div>
  {% endfor %}
  </div> 
</div>
</div>

{% endblock %}

{% block cart_panel %}
<div id="mySidepanel" class="sidepanel">
  <a href="#" class="closebtn">x</a>
  <div class='cart-container'>
    <div class="row" id="update-panel">
      
    </div>
    <hr/>

      <div class=" d-flex justify-content-between my-2">
        <div class="text-left font-weight-bold">Cart Sub-Total: </div>
        <div class="text-right font-weight-bold">
          <span class="currency">₱</span>
          <span class="cart-sub-total">0.00</span>
        </div>
      </div>
      
        
    <div class="d-flex text-right">
      <!-- <a class="d-block text-center btn btn-small btn-primary text-light" role="button">View Cart</a> -->
      <a class="d-block btn btn-primary btn-small text-center text-light"  href="{% url 'store:checkout' %}" role="button">Checkout</a>
    </div>
  </div>
  
</div>

{% endblock %}